// Generated by Wrangler by running `wrangler types`

interface Env {
	MEETING_CACHE: KVNamespace;
	SMTP_USER: "labh@collectivewin.ca";
	SMTP_PASSWORD: "muiawqzaotmckgsj";
	SMTP_HOST: "smtp.gmail.com";
	SMTP_PORT: "587";
	CF_ACCOUNT_ID: string;
	CF_API_TOKEN: string;
	RTK_APP_ID: string;
	OPENROUTER_API_KEY: string;
	OPENROUTER_MODEL: string;
	OPENROUTER_FREE_MODEL: string;
	OLLAMA_API_KEY: string;
	OLLAMA_BASE_URL: string;
	OLLAMA_MODEL: string;
	RECORDINGS_BUCKET: R2Bucket;
}
