name = "ve-rooom"
compatibility_date = "2024-09-01"
pages_build_output_dir = "dist"

[[kv_namespaces]]
binding = "MEETING_CACHE"
id = "fb0937accb414d98a8b9f84d81a6506a"

[[r2_buckets]]
binding = "RECORDINGS_BUCKET"
bucket_name = "ve-room"

[vars]
SMTP_API_URL = "https://ve-call.exe.xyz/smtp-api"
R2_BUCKET = "ve-room"